feat(ci): gas snapshot check

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -25,6 +25,8 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
+          # Ensure the PR branch is checked out.
+          ref: ${{ github.event.pull_request.head.sha }}
           submodules: recursive
 
       - name: Install Foundry
@@ -40,6 +42,16 @@ jobs:
 
       - name: Run Forge fmt
         run: forge fmt --check --root contracts
+
+      - name: Check gas snapshot
+        working-directory: contracts
+        run: |
+          forge snapshot
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error ::Gas snapshot is out of date. Run 'forge snapshot' and commit the result.";
+            git status
+            exit 1
+          fi
 
   cargo-test:
     name: Cargo Test
