ci: re-enable foundry gas snapshot

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -43,22 +43,18 @@ jobs:
       - name: Run Forge fmt
         run: forge fmt --check --root contracts
 
-      # This is broken because local vs. CI foundry mismatches gas even when
-      # on the same version.
-      #
-      # - name: Check Forge gas snapshot
-      #   working-directory: contracts
-      #   run: |
-      #     FOUNDRY_PROFILE=deploy forge snapshot --no-match-test "Fuzz"
-      #     if [[ -n "$(git status --porcelain)" ]]; then
-      #       echo "::error ::Gas snapshot is out of date. Run 'FOUNDRY_PROFILE=deploy forge snapshot --no-match-test \"Fuzz\"' and commit the result.";
-      #       echo "Git status:"
-      #       git status
-      #       echo ""
-      #       echo "Gas snapshot diff:"
-      #       git diff
-      #       exit 1
-      #     fi
+      - name: Check Forge gas snapshot
+        run: |
+          FOUNDRY_PROFILE=deploy forge snapshot --no-match-test "Fuzz" --root contracts
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error ::Gas snapshot is out of date. Run 'FOUNDRY_PROFILE=deploy forge snapshot --no-match-test \"Fuzz\"' and commit the result.";
+            echo "Git status:"
+            git status
+            echo ""
+            echo "Gas snapshot diff:"
+            git diff
+            exit 1
+          fi
 
   cargo-test:
     name: Cargo Test
